language: node_js
sudo: false
node_js:
  - 8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE final_project_db;'
install:
  - npm install
script:
  - npm run db:setup
env:
  - DB_HOST="127.0.0.1" DB_PORT="3306" DB_NAME="final_project_db"
    DB_USER="root" DB_PASSWORD=""
